version: "3.8"

services:
  eudoraai-nginx:
    image: nginx:latest
    container_name: eudoraai-nginx
    ports:
      - "80:80"
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./packages/frontend/dist:/usr/share/nginx/html:ro
      - ./ssl/cloudflare.crt:/etc/nginx/ssl/cloudflare.crt:ro
      - ./ssl/cloudflare.key:/etc/nginx/ssl/cloudflare.key:ro
    profiles:
      - application

volumes:
  postgres_data:
  # minio_data:
  minio_config:
